name: 'Test var'
description: 'Test var'

inputs:
  url:
    description: 'url'
    required: false
    default: 'http://hello-world.com'


runs:
  using: "composite"
  steps:
    - name: Echo input var
      run: echo "${{ inputs.url }}"
      shell: bash


